<?php


namespace sffi\phlegethon\service\Lock;


use sffi\phlegethon\util\DesCrypt;

class ValidateOwner extends \sffi\phlegethon\service\Base
{
    protected $router = 'lock/validate_owner';

    protected $args = [
        'account',
        'password',
        'lock_no'
    ];

    protected $rule = [
        'account' => 'require',
        'password' => 'require',
        'lock_no' => 'require'
    ];

    public function run(...$arguments)
    {
        $arguments = [$this->config['account'], DesCrypt::des_encrypt($this->config['password'], $this->config['key']), $arguments[0]];
        return parent::run(...$arguments); // TODO: Change the autogenerated stub
    }
}